### ISSUE TITLE
Problem with Docker (Daemon)

### ISSUE THREAD

**Issue by ghost** [mkotb/MineCloud#15]
Hey, it's me again c:
I think the old thread had became inactive? Now i've got the same error but iknow the Controller is sending the request to the Daemon, but the Daemon has got a error with Docker! 

When if it trying to start a Bungeecord Instance, i'm getting this error. (HTTP 409 Conflict).

P.S: Im using the newest version of Docker.

(Error, minecloud-daemon.err)
Sep 09, 2015 4:50:04 PM io.minecloud.daemon.Deployer deployBungeeCord
SCHWERWIEGEND: Was unable to create bungee with type BungeeInstance
com.spotify.docker.client.DockerRequestException: Request error: POST unix://localhost:80/v1.12/containers/create?name=BungeeInstance: 409
        at com.spotify.docker.client.DefaultDockerClient.propagate(DefaultDockerClient.java:1061)
        at com.spotify.docker.client.DefaultDockerClient.request(DefaultDockerClient.java:1010)
        at com.spotify.docker.client.DefaultDockerClient.createContainer(DefaultDockerClient.java:370)
        at io.minecloud.daemon.Deployer.deployBungeeCord(Deployer.java:198)
        at io.minecloud.daemon.Deployer.deployBungee(Deployer.java:140)
        at io.minecloud.daemon.MineCloudDaemon.lambda$new$5(MineCloudDaemon.java:132)
        at io.minecloud.db.redis.pubsub.SimpleRedisChannel.lambda$handle$1(SimpleRedisChannel.java:54)
        at java.lang.Iterable.forEach(Iterable.java:75)
        at io.minecloud.db.redis.pubsub.SimpleRedisChannel.handle(SimpleRedisChannel.java:52)
        at io.minecloud.db.redis.pubsub.ChannelPubSub.onMessage(ChannelPubSub.java:54)
        at redis.clients.jedis.BinaryJedisPubSub.process(BinaryJedisPubSub.java:102)
        at redis.clients.jedis.BinaryJedisPubSub.proceed(BinaryJedisPubSub.java:80)
        at redis.clients.jedis.BinaryJedis.subscribe(BinaryJedis.java:2844)
        at io.minecloud.db.redis.pubsub.RedisChannel.lambda$new$0(RedisChannel.java:34)
        at java.lang.Thread.run(Thread.java:745)
Caused by: com.spotify.docker.client.shaded.javax.ws.rs.ClientErrorException: HTTP 409 Conflict
        at org.glassfish.jersey.client.JerseyInvocation.createExceptionForFamily(JerseyInvocation.java:991)
        at org.glassfish.jersey.client.JerseyInvocation.convertToException(JerseyInvocation.java:975)
        at org.glassfish.jersey.client.JerseyInvocation.translate(JerseyInvocation.java:795)
        at org.glassfish.jersey.client.JerseyInvocation.access$500(JerseyInvocation.java:91)
        at org.glassfish.jersey.client.JerseyInvocation$5.completed(JerseyInvocation.java:756)
        at org.glassfish.jersey.client.ClientRuntime.processResponse(ClientRuntime.java:189)
        at org.glassfish.jersey.client.ClientRuntime.access$300(ClientRuntime.java:74)
        at org.glassfish.jersey.client.ClientRuntime$1.run(ClientRuntime.java:171)
        at org.glassfish.jersey.internal.Errors$1.call(Errors.java:271)
        at org.glassfish.jersey.internal.Errors$1.call(Errors.java:267)
        at org.glassfish.jersey.internal.Errors.process(Errors.java:315)
        at org.glassfish.jersey.internal.Errors.process(Errors.java:297)
        at org.glassfish.jersey.internal.Errors.process(Errors.java:267)
        at org.glassfish.jersey.process.internal.RequestScope.runInScope(RequestScope.java:320)
        at org.glassfish.jersey.client.ClientRuntime$2.run(ClientRuntime.java:201)
        at java.util.concurrent.Executors$RunnableAdapter.call(Executors.java:511)
        at java.util.concurrent.FutureTask.run(FutureTask.java:266)
        at java.util.concurrent.ThreadPoolExecutor.runWorker(ThreadPoolExecutor.java:1142)
        at java.util.concurrent.ThreadPoolExecutor$Worker.run(ThreadPoolExecutor.java:617)
        ... 1 more

Sep 09, 2015 4:50:10 PM io.minecloud.daemon.MineCloudDaemon lambda$new$10
INFORMATION: Killed dead container b1252b5be13404d5069cf74f90db4e3c23fcb3c3890a0e08e17416163046618f (/BungeeInstance)

**Comment by mkotb** [comment]
There looks to be a container already created for the bungee, then shuts down immediately. The container will exit immediately if your mount setup is not setup correctly.

Ensure your scripts and files in `/mnt/minecloud` are correct.
Do you have multiple controllers running?

**Comment by ghost** [comment]
Hmm, i don't know it's possible. Another thing is, the init.d script is'nt working on startup i've have to start it manually... (possibly because redis) I've to start it manually
Scripts are correctly i hope... (java -Xms500M -Xmx500M -jar bungee.jar) in the script file

**Comment by ghost** [comment]
Now i have tried to fix bugs but...

Sep 12, 2015 7:13:04 PM org.mongodb.morphia.logging.MorphiaLoggerFactory chooseLoggerFactory
INFORMATION: LoggerImplFactory set to org.mongodb.morphia.logging.jdk.JDKLoggerFactory
SLF4J: Failed to load class "org.slf4j.impl.StaticLoggerBinder".
SLF4J: Defaulting to no-operation (NOP) logger implementation
SLF4J: See http://www.slf4j.org/codes.html#StaticLoggerBinder for further details.
Exception in thread "Thread-4" java.util.NoSuchElementException: No value present
        at java.util.Optional.get(Optional.java:135)
        at io.minecloud.daemon.StatisticsWatcher.lambda$run$14(StatisticsWatcher.java:91)
        at java.util.stream.Streams$RangeIntSpliterator.forEachRemaining(Streams.java:110)
        at java.util.stream.IntPipeline$Head.forEach(IntPipeline.java:557)
        at io.minecloud.daemon.StatisticsWatcher.run(StatisticsWatcher.java:86)
