### ISSUE TITLE
Okay, whut? - Problems with the System.

### ISSUE THREAD

**Issue by ghost** [mkotb/MineCloud#24]
All is setup, all is connected... BungeeCord is started, but the server does not start. Why?

```
Dec 21, 2015 2:33:20 PM org.mongodb.morphia.logging.MorphiaLoggerFactory chooseLoggerFactory
INFO: LoggerImplFactory set to org.mongodb.morphia.logging.jdk.JDKLoggerFactory
SLF4J: Failed to load class "org.slf4j.impl.StaticLoggerBinder".
SLF4J: Defaulting to no-operation (NOP) logger implementation
SLF4J: See http://www.slf4j.org/codes.html#StaticLoggerBinder for further details.
Exception in thread "Thread-4" java.util.NoSuchElementException: No value present
        at java.util.Optional.get(Optional.java:135)
        at io.minecloud.daemon.StatisticsWatcher.lambda$run$14(StatisticsWatcher.java:91)
        at java.util.stream.Streams$RangeIntSpliterator.forEachRemaining(Streams.java:110)
        at java.util.stream.IntPipeline$Head.forEach(IntPipeline.java:557)
        at io.minecloud.daemon.StatisticsWatcher.run(StatisticsWatcher.java:86)
Dec 21, 2015 2:33:22 PM io.minecloud.daemon.MineCloudDaemon lambda$new$10
INFO: Killed dead container 9f055da50824b26b39759cd5e1d0bb6f55c9eeed1d44556987b41e505d766869 (/grave_poincare)
Dec 21, 2015 2:33:22 PM io.minecloud.daemon.MineCloudDaemon lambda$new$10
INFO: Killed dead container 50ddb56da159e8701ac4942c1f1a6e3f48206d3f907db81a7bf75e4d6b0fa615 (/pensive_newton)
Dec 21, 2015 3:21:19 PM io.minecloud.daemon.Deployer deployBungeeCord
INFO: Started bungee Bungee.212.224.74.222 with container id 212.224.74.222
```

```
INFO: LoggerImplFactory set to org.mongodb.morphia.logging.jdk.JDKLoggerFactory
Exception in thread "main" java.lang.NullPointerException
        at io.minecloud.models.network.Network.deployServer(Network.java:78)
        at io.minecloud.controller.Controller.lambda$null$5(Controller.java:111)
        at java.util.stream.Streams$RangeIntSpliterator.forEachRemaining(Streams.java:110)
        at java.util.stream.IntPipeline$Head.forEach(IntPipeline.java:557)
        at io.minecloud.controller.Controller.lambda$null$6(Controller.java:104)
        at java.util.ArrayList.forEach(ArrayList.java:1249)
        at io.minecloud.controller.Controller.lambda$new$7(Controller.java:75)
        at java.util.ArrayList.forEach(ArrayList.java:1249)
        at io.minecloud.controller.Controller.<init>(Controller.java:61)
        at io.minecloud.controller.Controller.main(Controller.java:157)
```

![servertype](https://cloud.githubusercontent.com/assets/13961579/11940607/076022b2-a82a-11e5-94ae-078c6a2ccac1.PNG)
![network](https://cloud.githubusercontent.com/assets/13961579/11940608/076313e6-a82a-11e5-85d9-2aaae7675ee2.PNG)
![node](https://cloud.githubusercontent.com/assets/13961579/11940609/07b72bfc-a82a-11e5-9194-1acf75040f8f.PNG)

All what i can tell is there is something wrong with the node, because the error refer to 

```
os.writeString(node.name());
```

**Comment by ghost** [comment]
Is it bad if the thread number is not right?
Now the Bungeecord is'nt starting anymore (after editing the thread number). I stopped both services and killed with the "docker kill" command the Bungee. Now this is the only thing i see, that has todo with Bungeecord.

```
INFO: Killed dead container d8babef03d45752493dc4fca3ed0e462a462a74d1b34e81b1f5550120282494b (/Bungee)
```

And now, i don't have any ideas.
![whut](https://cloud.githubusercontent.com/assets/13961579/11954508/600794e8-a8a9-11e5-9ccd-37e9e63fd2a0.PNG)
Tries, removing the second added node, failed the same way.

EDIT: It looks like there is a mistake made in coding... The node exists and is editable with the cli but not removeable in the networktype. Again, it says this node exists but isnt added to the network... I think this is the reason for the other errors. Server are removable or addable, also bungees.

Edit2: Reinstalled mongo, same problems.

```
Exception in thread "Thread-4" java.util.NoSuchElementException: No value present at java.util.Optional.get(Optional.java:135) at io.minecloud.daemon.StatisticsWatcher.lambda$run$14(StatisticsWatcher.java:91) at java.util.stream.Streams$RangeIntSpliterator.forEachRemaining(Streams.java:110) at java.util.stream.IntPipeline$Head.forEach(IntPipeline.java:557) at io.minecloud.daemon.StatisticsWatcher.run(StatisticsWatcher.java:86)
```

Has been fixeed by correcting the thread number

After more fixing, the controller is spammed by this.

```

Dec 23, 2015 3:48:07 AM org.mongodb.morphia.logging.MorphiaLoggerFactory chooseLoggerFactory
INFO: LoggerImplFactory set to org.mongodb.morphia.logging.jdk.JDKLoggerFactory
Dec 23, 2015 3:48:08 AM io.minecloud.controller.Controller lambda$null$5
INFO: Sent deploy message to AimPrime for server type Lobby on Network
Dec 23, 2015 3:48:18 AM io.minecloud.controller.Controller lambda$null$5
INFO: Sent deploy message to AimPrime for server type Lobby on Network
Dec 23, 2015 3:48:28 AM io.minecloud.controller.Controller lambda$null$5
INFO: Sent deploy message to AimPrime for server type Lobby on Network
Dec 23, 2015 3:48:39 AM io.minecloud.controller.Controller lambda$null$5
INFO: Sent deploy message to AimPrime for server type Lobby on Network
Dec 23, 2015 3:48:49 AM io.minecloud.controller.Controller lambda$null$5
INFO: Sent deploy message to AimPrime for server type Lobby on Network
Dec 23, 2015 3:48:59 AM io.minecloud.controller.Controller lambda$null$5
INFO: Sent deploy message to AimPrime for server type Lobby on Network
Dec 23, 2015 3:49:09 AM io.minecloud.controller.Controller lambda$null$5
INFO: Sent deploy message to AimPrime for server type Lobby on Network
Dec 23, 2015 3:49:20 AM io.minecloud.controller.Controller lambda$null$5
INFO: Sent deploy message to AimPrime for server type Lobby on Network
Dec 23, 2015 3:49:30 AM io.minecloud.controller.Controller lambda$null$5
INFO: Sent deploy message to AimPrime for server type Lobby on Network
Dec 23, 2015 3:49:40 AM io.minecloud.controller.Controller lambda$null$5
INFO: Sent deploy message to AimPrime for server type Lobby on Network
Dec 23, 2015 3:49:50 AM io.minecloud.controller.Controller lambda$null$5
INFO: Sent deploy message to AimPrime for server type Lobby on Network
```

The daemon log is still empty, except for the message that the logger is set to NOP.

**Comment by ghost** [comment]
Oki, got it! But i have one problem... The controller & daemon connected. But i got this from my server (bukkit + bungee) log:

```

Caused by: com.mongodb.MongoTimeoutException: Timed out after 10000 ms while waiting to connect. Client view of cluster state is {type=Unknown, servers=[{address=localhost:27017, type=Unknown, state=Connecting, exception={com.mongodb.MongoException$Network: Exception opening the socket}, caused by {java.net.ConnectException: Connection refused}}]
        at com.mongodb.BaseCluster.getDescription(BaseCluster.java:128)
        at com.mongodb.DBTCPConnector.getClusterDescription(DBTCPConnector.java:394)
        at com.mongodb.DBTCPConnector.getType(DBTCPConnector.java:571)
        at com.mongodb.DBTCPConnector.isMongosConnection(DBTCPConnector.java:368)
        at com.mongodb.Mongo.isMongosConnection(Mongo.java:622)
        at com.mongodb.DBCursor._check(DBCursor.java:494)
        at com.mongodb.DBCursor._hasNext(DBCursor.java:621)
        at com.mongodb.DBCursor.hasNext(DBCursor.java:657)
        at org.mongodb.morphia.query.MorphiaIterator.hasNext(MorphiaIterator.java:50)
        at org.mongodb.morphia.query.QueryImpl.get(QueryImpl.java:421)
        at org.mongodb.morphia.dao.BasicDAO.findOne(BasicDAO.java:214)
        at io.minecloud.db.mongo.AbstractMongoRepository.findFirst(AbstractMongoRepository.java:41)
        at io.minecloud.bukkit.MineCloudPlugin$1.run(MineCloudPlugin.java:71)
        at org.bukkit.craftbukkit.v1_8_R3.scheduler.CraftTask.run(CraftTask.java:71)
        at org.bukkit.craftbukkit.v1_8_R3.scheduler.CraftAsyncTask.run(CraftAsyncTask.java:53)
        ... 3 more
```

**Comment by ghost** [comment]
Fixed :)
