### ISSUE TITLE
Exception in thread "MineCloud - Channel 'bungee-create Thread"

### ISSUE THREAD

**Issue by DDynamic** [mkotb/MineCloud#26]
Hello,
I am trying to install MineCloud on a Ubuntu 14.04 Dedicated Server. When I first ran the controller, I got a simple auth error I fixed. However, I get this new error. Could someone help point me in the right direction?

```
# java -jar controller/target/controller-1.0.jar
Dec 27, 2015 4:16:22 PM org.mongodb.morphia.logging.MorphiaLoggerFactory chooseLoggerFactory
INFO: LoggerImplFactory set to org.mongodb.morphia.logging.jdk.JDKLoggerFactory
Exception in thread "MineCloud - Channel 'bungee-create Thread" Exception in thread "MineCloud - Channel 'server-create Thread" redis.clients.jedis.exceptions.JedisConnectionException: Could not get a resource from the pool
    at redis.clients.util.Pool.getResource(Pool.java:50)
    at redis.clients.jedis.JedisPool.getResource(JedisPool.java:88)
    at io.minecloud.db.redis.RedisDatabase.grabResource(RedisDatabase.java:81)
    at io.minecloud.db.redis.pubsub.RedisChannel.lambda$new$9(RedisChannel.java:33)
    at java.lang.Thread.run(Thread.java:745)
Caused by: redis.clients.jedis.exceptions.JedisDataException: ERR Client sent AUTH, but no password is set
    at redis.clients.jedis.Protocol.processError(Protocol.java:113)
    at redis.clients.jedis.Protocol.process(Protocol.java:138)
    at redis.clients.jedis.Protocol.read(Protocol.java:192)
    at redis.clients.jedis.Connection.readProtocolWithCheckingBroken(Connection.java:282)
    at redis.clients.jedis.Connection.getStatusCodeReply(Connection.java:181)
    at redis.clients.jedis.BinaryJedis.auth(BinaryJedis.java:1930)
    at redis.clients.jedis.JedisFactory.makeObject(JedisFactory.java:71)
    at org.apache.commons.pool2.impl.GenericObjectPool.create(GenericObjectPool.java:819)
    at org.apache.commons.pool2.impl.GenericObjectPool.borrowObject(GenericObjectPool.java:452)
    at org.apache.commons.pool2.impl.GenericObjectPool.borrowObject(GenericObjectPool.java:360)
    at redis.clients.util.Pool.getResource(Pool.java:48)
    ... 4 more
Dec 27, 2015 4:16:23 PM io.minecloud.db.redis.RedisDatabase connected
WARNING: Redis connection had died, reconnecting.
redis.clients.jedis.exceptions.JedisConnectionException: Could not get a resource from the pool
    at redis.clients.util.Pool.getResource(Pool.java:50)
    at redis.clients.jedis.JedisPool.getResource(JedisPool.java:88)
    at io.minecloud.db.redis.RedisDatabase.grabResource(RedisDatabase.java:81)
    at io.minecloud.db.redis.pubsub.RedisChannel.lambda$new$9(RedisChannel.java:33)
    at java.lang.Thread.run(Thread.java:745)
Caused by: redis.clients.jedis.exceptions.JedisDataException: ERR Client sent AUTH, but no password is set
    at redis.clients.jedis.Protocol.processError(Protocol.java:113)
    at redis.clients.jedis.Protocol.process(Protocol.java:138)
    at redis.clients.jedis.Protocol.read(Protocol.java:192)
    at redis.clients.jedis.Connection.readProtocolWithCheckingBroken(Connection.java:282)
    at redis.clients.jedis.Connection.getStatusCodeReply(Connection.java:181)
    at redis.clients.jedis.BinaryJedis.auth(BinaryJedis.java:1930)
    at redis.clients.jedis.JedisFactory.makeObject(JedisFactory.java:71)
    at org.apache.commons.pool2.impl.GenericObjectPool.create(GenericObjectPool.java:819)
    at org.apache.commons.pool2.impl.GenericObjectPool.borrowObject(GenericObjectPool.java:452)
    at org.apache.commons.pool2.impl.GenericObjectPool.borrowObject(GenericObjectPool.java:360)
    at redis.clients.util.Pool.getResource(Pool.java:48)
    ... 4 more
Exception in thread "main" com.mongodb.CommandFailureException: { "serverUsed" : "localhost:27017" , "ok" : 0.0 , "errmsg" : "auth failed" , "code" : 18}
    at com.mongodb.CommandResult.getException(CommandResult.java:76)
    at com.mongodb.CommandResult.throwOnError(CommandResult.java:140)
    at com.mongodb.DBPort$NativeAuthenticator.authenticate(DBPort.java:986)
    at com.mongodb.DBPort.authenticate(DBPort.java:432)
    at com.mongodb.DBPort.checkAuth(DBPort.java:443)
    at com.mongodb.DBTCPConnector.innerCall(DBTCPConnector.java:289)
    at com.mongodb.DBTCPConnector.call(DBTCPConnector.java:269)
    at com.mongodb.DBCollectionImpl.find(DBCollectionImpl.java:84)
    at com.mongodb.DBCollectionImpl.find(DBCollectionImpl.java:66)
    at com.mongodb.DBCursor._check(DBCursor.java:498)
    at com.mongodb.DBCursor._hasNext(DBCursor.java:621)
    at com.mongodb.DBCursor.hasNext(DBCursor.java:657)
    at org.mongodb.morphia.query.MorphiaIterator.hasNext(MorphiaIterator.java:50)
    at org.mongodb.morphia.query.QueryImpl.asList(QueryImpl.java:323)
    at io.minecloud.db.mongo.AbstractMongoRepository.models(AbstractMongoRepository.java:51)
    at io.minecloud.controller.Controller.<init>(Controller.java:60)
    at io.minecloud.controller.Controller.main(Controller.java:157)
```

**Thanks!**

**Comment by FluuxyTv** [comment]
```
Caused by: redis.clients.jedis.exceptions.JedisDataException: ERR Client sent AUTH, but no password is set
```
Looks like you set a password in the details.properties for minecloud, but the not for your redis server.

**Comment by DDynamic** [comment]
@FluuxyTv thanks for the reply.

I set my password in `redis.conf`:

```
requirepass SECRETPASSWORD
```

As for the MonogoDB error, I restarted it and this is my new full error log.

```
Dec 27, 2015 5:42:44 PM org.mongodb.morphia.logging.MorphiaLoggerFactory chooseLoggerFactory
INFO: LoggerImplFactory set to org.mongodb.morphia.logging.jdk.JDKLoggerFactory
Exception in thread "MineCloud - Channel 'server-create Thread" Exception in thread "MineCloud - Channel 'bungee-create Thread" redis.clients.jedis.exceptions.JedisConnectionException: Could not get a resource from the pool
    at redis.clients.util.Pool.getResource(Pool.java:50)
    at redis.clients.jedis.JedisPool.getResource(JedisPool.java:88)
    at io.minecloud.db.redis.RedisDatabase.grabResource(RedisDatabase.java:81)
    at io.minecloud.db.redis.pubsub.RedisChannel.lambda$new$9(RedisChannel.java:33)
    at java.lang.Thread.run(Thread.java:745)
Caused by: redis.clients.jedis.exceptions.JedisDataException: ERR Client sent AUTH, but no password is set
    at redis.clients.jedis.Protocol.processError(Protocol.java:113)
    at redis.clients.jedis.Protocol.process(Protocol.java:138)
    at redis.clients.jedis.Protocol.read(Protocol.java:192)
    at redis.clients.jedis.Connection.readProtocolWithCheckingBroken(Connection.java:282)
    at redis.clients.jedis.Connection.getStatusCodeReply(Connection.java:181)
    at redis.clients.jedis.BinaryJedis.auth(BinaryJedis.java:1930)
    at redis.clients.jedis.JedisFactory.makeObject(JedisFactory.java:71)
    at org.apache.commons.pool2.impl.GenericObjectPool.create(GenericObjectPool.java:819)
    at org.apache.commons.pool2.impl.GenericObjectPool.borrowObject(GenericObjectPool.java:452)
    at org.apache.commons.pool2.impl.GenericObjectPool.borrowObject(GenericObjectPool.java:360)
    at redis.clients.util.Pool.getResource(Pool.java:48)
    ... 4 more
Dec 27, 2015 5:42:44 PM io.minecloud.db.redis.RedisDatabase connected
WARNING: Redis connection had died, reconnecting.
redis.clients.jedis.exceptions.JedisConnectionException: Could not get a resource from the pool
    at redis.clients.util.Pool.getResource(Pool.java:50)
    at redis.clients.jedis.JedisPool.getResource(JedisPool.java:88)
    at io.minecloud.db.redis.RedisDatabase.grabResource(RedisDatabase.java:81)
    at io.minecloud.db.redis.pubsub.RedisChannel.lambda$new$9(RedisChannel.java:33)
    at java.lang.Thread.run(Thread.java:745)
Caused by: redis.clients.jedis.exceptions.JedisDataException: ERR Client sent AUTH, but no password is set
    at redis.clients.jedis.Protocol.processError(Protocol.java:113)
    at redis.clients.jedis.Protocol.process(Protocol.java:138)
    at redis.clients.jedis.Protocol.read(Protocol.java:192)
    at redis.clients.jedis.Connection.readProtocolWithCheckingBroken(Connection.java:282)
    at redis.clients.jedis.Connection.getStatusCodeReply(Connection.java:181)
    at redis.clients.jedis.BinaryJedis.auth(BinaryJedis.java:1930)
    at redis.clients.jedis.JedisFactory.makeObject(JedisFactory.java:71)
    at org.apache.commons.pool2.impl.GenericObjectPool.create(GenericObjectPool.java:819)
    at org.apache.commons.pool2.impl.GenericObjectPool.borrowObject(GenericObjectPool.java:452)
    at org.apache.commons.pool2.impl.GenericObjectPool.borrowObject(GenericObjectPool.java:360)
    at redis.clients.util.Pool.getResource(Pool.java:48)
    ... 4 more
Exception in thread "main" com.mongodb.MongoTimeoutException: Timed out after 10000 ms while waiting to connect. Client view of cluster state is {type=Unknown, servers=[{address=localhost:27017, type=Unknown, state=Connecting, exception={com.mongodb.MongoException$Network: Exception opening the socket}, caused by {java.net.ConnectException: Connection refused}}]
    at com.mongodb.BaseCluster.getDescription(BaseCluster.java:128)
    at com.mongodb.DBTCPConnector.getClusterDescription(DBTCPConnector.java:394)
    at com.mongodb.DBTCPConnector.getType(DBTCPConnector.java:571)
    at com.mongodb.DBTCPConnector.isMongosConnection(DBTCPConnector.java:368)
    at com.mongodb.Mongo.isMongosConnection(Mongo.java:622)
    at com.mongodb.DBCursor._check(DBCursor.java:494)
    at com.mongodb.DBCursor._hasNext(DBCursor.java:621)
    at com.mongodb.DBCursor.hasNext(DBCursor.java:657)
    at org.mongodb.morphia.query.MorphiaIterator.hasNext(MorphiaIterator.java:50)
    at org.mongodb.morphia.query.QueryImpl.asList(QueryImpl.java:323)
    at io.minecloud.db.mongo.AbstractMongoRepository.models(AbstractMongoRepository.java:51)
    at io.minecloud.controller.Controller.<init>(Controller.java:60)
    at io.minecloud.controller.Controller.main(Controller.java:157)
```

**Comment by FluuxyTv** [comment]
Same, make sure in your redis.conf, you have not a #. Did you restart the redis server?

**Comment by csh** [comment]
> Caused by: redis.clients.jedis.exceptions.JedisDataException: ERR Client sent AUTH, but no password is set

The password that Minecloud is attempting to use is either `null` or empty.
