### ISSUE TITLE
Bungee plugin connection

### ISSUE THREAD

**Issue by eXAccept** [mkotb/MineCloud#31]
Hello!
java.lang.IllegalArgumentException: Invalid database name format. Database name is either empty or it contains spaces.
    at com.mongodb.DB.<init>(DB.java:67)
    at com.mongodb.DBApiLayer.<init>(DBApiLayer.java:58)
    at com.mongodb.Mongo.getDB(Mongo.java:344)
    at io.minecloud.db.mongo.MongoDatabase.setup(MongoDatabase.java:109)
    at io.minecloud.MineCloud.initiateMongo(MineCloud.java:162)
    at io.minecloud.MineCloud.environmentSetup(MineCloud.java:76)
    at io.minecloud.bungee.MineCloudPlugin.onEnable(MineCloudPlugin.java:59)
    at net.md_5.bungee.api.plugin.PluginManager.enablePlugins(PluginManager.java)
    at net.md_5.bungee.BungeeCord.start(BungeeCord.java)
    at net.md_5.bungee.BungeeCordLauncher.main(BungeeCordLauncher.java)
    at net.md_5.bungee.Bootstrap.main(Bootstrap.java)

Where it takes data to mongodb?

**Comment by mkotb** [comment]
This is invalid configuration of the config.
