### ISSUE TITLE
Timeouts

### ISSUE THREAD

**Issue by exception** [mkotb/MineCloud#33]
```
2016-01-24T14:20:52,218+0000 [WARN] Exception in thread "MineCloud - Channel 'server-shutdown-notif Thread" 
2016-01-24T14:20:52,218+0000 [WARN] redis.clients.jedis.exceptions.JedisConnectionException: Could not get a resource from the pool
2016-01-24T14:20:52,218+0000 [WARN]     at redis.clients.util.Pool.getResource(Pool.java:50)
2016-01-24T14:20:52,218+0000 [WARN]     at redis.clients.jedis.JedisPool.getResource(JedisPool.java:88)
2016-01-24T14:20:52,218+0000 [WARN]     at io.minecloud.db.redis.RedisDatabase.grabResource(RedisDatabase.java:81)
2016-01-24T14:20:52,218+0000 [WARN]     at io.minecloud.db.redis.pubsub.RedisChannel.lambda$new$2(RedisChannel.java:33)
2016-01-24T14:20:52,218+0000 [WARN]     at io.minecloud.db.redis.pubsub.RedisChannel$$Lambda$8/1323414799.run(Unknown Source)
2016-01-24T14:20:52,218+0000 [WARN]     at java.lang.Thread.run(Thread.java:745)
2016-01-24T14:20:52,219+0000 [WARN] Caused by: redis.clients.jedis.exceptions.JedisConnectionException: java.net.SocketTimeoutException: connect timed out
2016-01-24T14:20:52,219+0000 [WARN]     at redis.clients.jedis.Connection.connect(Connection.java:148)
2016-01-24T14:20:52,219+0000 [WARN]     at redis.clients.jedis.BinaryClient.connect(BinaryClient.java:75)
2016-01-24T14:20:52,219+0000 [WARN]     at redis.clients.jedis.BinaryJedis.connect(BinaryJedis.java:1572)
2016-01-24T14:20:52,219+0000 [WARN]     at redis.clients.jedis.JedisFactory.makeObject(JedisFactory.java:69)
2016-01-24T14:20:52,219+0000 [WARN]     at org.apache.commons.pool2.impl.GenericObjectPool.create(GenericObjectPool.java:819)
2016-01-24T14:20:52,219+0000 [WARN]     at org.apache.commons.pool2.impl.GenericObjectPool.borrowObject(GenericObjectPool.java:452)
2016-01-24T14:20:52,219+0000 [WARN]     at org.apache.commons.pool2.impl.GenericObjectPool.borrowObject(GenericObjectPool.java:360)
2016-01-24T14:20:52,219+0000 [WARN]     at redis.clients.util.Pool.getResource(Pool.java:48)
2016-01-24T14:20:52,219+0000 [WARN]     ... 5 more
2016-01-24T14:20:52,220+0000 [WARN] Caused by: java.net.SocketTimeoutException: connect timed out
2016-01-24T14:20:52,220+0000 [WARN]     at java.net.PlainSocketImpl.socketConnect(Native Method)
2016-01-24T14:20:52,220+0000 [WARN]     at java.net.AbstractPlainSocketImpl.doConnect(AbstractPlainSocketImpl.java:345)
2016-01-24T14:20:52,220+0000 [WARN]     at java.net.AbstractPlainSocketImpl.connectToAddress(AbstractPlainSocketImpl.java:206)
2016-01-24T14:20:52,220+0000 [WARN]     at java.net.AbstractPlainSocketImpl.connect(AbstractPlainSocketImpl.java:188)
2016-01-24T14:20:52,220+0000 [WARN]     at java.net.SocksSocketImpl.connect(SocksSocketImpl.java:392)
2016-01-24T14:20:52,220+0000 [WARN]     at java.net.Socket.connect(Socket.java:589)
2016-01-24T14:20:52,220+0000 [WARN]     at redis.clients.jedis.Connection.connect(Connection.java:142)
2016-01-24T14:20:52,220+0000 [WARN]     ... 12 more
```

This is getting out of hand already.

**Comment by mkotb** [comment]
It'll timeout after one second I believe, I could bump it up if it appears to cause issues for you?

**Comment by exception** [comment]
According to our redis logs, and @Sigurs we're not returning any clients or pools.

``` shell
# Clients
connected_clients:471
client_longest_output_list:0
client_biggest_input_buf:0
blocked_clients:0
```

This might be a cause for the issues.
