### ISSUE TITLE
Problems with the Controller

### ISSUE THREAD

**Issue by ghost** [mkotb/MineCloud#9]
Im getting this error. Copied from the log.

Exception in thread "main" java.lang.NullPointerException
        at io.minecloud.models.network.Network.deployServer(Network.java:79)
        at io.minecloud.controller.Controller.lambda$null$5(Controller.java:113)
        at java.util.stream.Streams$RangeIntSpliterator.forEachRemaining(Streams.java:110)
        at java.util.stream.IntPipeline$Head.forEach(IntPipeline.java:557)
        at io.minecloud.controller.Controller.lambda$null$6(Controller.java:106)
        at java.util.ArrayList.forEach(ArrayList.java:1249)
        at io.minecloud.controller.Controller.lambda$new$7(Controller.java:77)
        at java.util.ArrayList.forEach(ArrayList.java:1249)
        at io.minecloud.controller.Controller.<init>(Controller.java:63)
        at io.minecloud.controller.Controller.main(Controller.java:159)

Thanks for any help.

**Comment by mkotb** [comment]
No node was found, meaning that either you have not added any nodes or they
are not added to the network type

**Comment by ghost** [comment]
Thanks for the fast answer.

Ive created a node and a network already.

**Comment by mkotb** [comment]
No worries. When you create the node you need to add that node to be
assigned to your network. You can do that in the MineCloud CLI by entering
the network type prompt, then running the add-node command.

**Comment by ghost** [comment]
I know, i looked into all Handler classes and added all. I will look tomorrow to it and setup it again

**Comment by mkotb** [comment]
So the node is added to the network?

**Comment by ghost** [comment]
At the moment i cant check that... Im sure i checked all with !show and pushed them.

**Comment by ghost** [comment]
Thanks for the great support, i will sleep a night over it.

**Comment by ghost** [comment]
All configuration's are setup. One Node and one Network exists. But the controller give me still the same error

**Comment by ghost** [comment]
Exception in thread "main" java.lang.NullPointerException
        at io.minecloud.models.network.Network.deployServer(Network.java:79)
        at io.minecloud.controller.Controller.lambda$null$5(Controller.java:113)
        at java.util.stream.Streams$RangeIntSpliterator.forEachRemaining(Streams.java:110)
        at java.util.stream.IntPipeline$Head.forEach(IntPipeline.java:557)
        at io.minecloud.controller.Controller.lambda$null$6(Controller.java:106)
        at java.util.ArrayList.forEach(ArrayList.java:1249)
        at io.minecloud.controller.Controller.lambda$new$7(Controller.java:77)
        at java.util.ArrayList.forEach(ArrayList.java:1249)
        at io.minecloud.controller.Controller.<init>(Controller.java:63)
        at io.minecloud.controller.Controller.main(Controller.java:159)

**Comment by mkotb** [comment]
Send me the !show for the network type

**Comment by ghost** [comment]
![test](https://cloud.githubusercontent.com/assets/13961579/9487058/c4d1adc4-4bce-11e5-88ac-6da1f1dcba90.PNG)

**Comment by ghost** [comment]
ignore the errors above, i re-installed it hoping for fixing errors and correct mistakes.

**Comment by mkotb** [comment]
Can you show me the specifications for the node type? The controller will ignore a node if it doesn't have enough allocated RAM to place the server on.

**Comment by ghost** [comment]
Yeah, now it's a test mini-root but have enough ram to start with a little cloud, moving to the root if all working.
![controller](https://cloud.githubusercontent.com/assets/13961579/9487212/c1c6e4f4-4bcf-11e5-8487-53aa437eddd8.PNG)

**Comment by mkotb** [comment]
How much RAM does the server type require?

**Comment by ghost** [comment]
500mb = Bungee, 500mb Lobby-Server. Created 2 testplugins and 1 testworld.
I'm not expect many players on the mini-root.

**Comment by mkotb** [comment]
Does the bungee start?

**Comment by ghost** [comment]
Nope.
What about the Bungee folder, how the jar must be named and whats about the shell script?

**Comment by mkotb** [comment]
The script must be named `start.sh`, the jar can be named whatever you wish as you are specifying in the script how you want to start the process.

Can you go into mongo and show me the raw BSON entry for the network type?

**Comment by ghost** [comment]
I have, but there are specials how the script should be built?
I don't know much about mongodb-console commands.

**Comment by mkotb** [comment]
A simple example is just `java -jar bungee.jar`, which expects the jar to be called "bungee.jar"

**Comment by ghost** [comment]
Ohh, okay... My vault i have got a empty.sh caused by no-perm with my ftp acc... The script should makes executable? Is it usefull to have screens there, or is that not supported.
EDIT: Bukkit folder not defined -.-

**Comment by ghost** [comment]
I've created the folders, and defined the shell scripts. Get the same error in the log.

**Comment by mkotb** [comment]
As for the error, refer to my last question:

> Can you go into mongo and show me the raw BSON entry for the network type?

The script must be called `start.sh` as I mentioned before. Do not use screens for this, we are putting the servers in the docker container for a reason.

On that note, I'm off for the night.

**Comment by ghost** [comment]
Ohh, in my town it's now day. See u tomorrow dude.

**Comment by ghost** [comment]
Found errors while checking logs on daemon. I don't know if it helps.
Daemon:
SCHWERWIEGEND: Was unable to create bungee with type BungeeInstance
com.spotify.docker.client.DockerRequestException: Request error: POST unix://localhost:80/v1.12/containers/create?name=BungeeInstance: 409
        at com.spotify.docker.client.DefaultDockerClient.propagate(DefaultDockerClient.java:1061)
        at com.spotify.docker.client.DefaultDockerClient.request(DefaultDockerClient.java:1010)
        at com.spotify.docker.client.DefaultDockerClient.createContainer(DefaultDockerClient.java:370)
        at io.minecloud.daemon.Deployer.deployBungeeCord(Deployer.java:198)
        at io.minecloud.daemon.Deployer.deployBungee(Deployer.java:140)
        at io.minecloud.daemon.MineCloudDaemon.lambda$new$5(MineCloudDaemon.java:132)
        at io.minecloud.db.redis.pubsub.SimpleRedisChannel.lambda$handle$1(SimpleRedisChannel.java:54)
        at java.lang.Iterable.forEach(Iterable.java:75)
        at io.minecloud.db.redis.pubsub.SimpleRedisChannel.handle(SimpleRedisChannel.java:52)
        at io.minecloud.db.redis.pubsub.ChannelPubSub.onMessage(ChannelPubSub.java:54)
        at redis.clients.jedis.BinaryJedisPubSub.process(BinaryJedisPubSub.java:102)
        at redis.clients.jedis.BinaryJedisPubSub.proceed(BinaryJedisPubSub.java:80)
        at redis.clients.jedis.BinaryJedis.subscribe(BinaryJedis.java:2844)
        at io.minecloud.db.redis.pubsub.RedisChannel.lambda$new$0(RedisChannel.java:34)
        at java.lang.Thread.run(Thread.java:745)
Caused by: com.spotify.docker.client.shaded.javax.ws.rs.ClientErrorException: HTTP 409 Conflict
        at org.glassfish.jersey.client.JerseyInvocation.createExceptionForFamily(JerseyInvocation.java:991)
        at org.glassfish.jersey.client.JerseyInvocation.convertToException(JerseyInvocation.java:975)
        at org.glassfish.jersey.client.JerseyInvocation.translate(JerseyInvocation.java:795)
        at org.glassfish.jersey.client.JerseyInvocation.access$500(JerseyInvocation.java:91)
        at org.glassfish.jersey.client.JerseyInvocation$5.completed(JerseyInvocation.java:756)
        at org.glassfish.jersey.client.ClientRuntime.processResponse(ClientRuntime.java:189)
        at org.glassfish.jersey.client.ClientRuntime.access$300(ClientRuntime.java:74)
        at org.glassfish.jersey.client.ClientRuntime$1.run(ClientRuntime.java:171)
        at org.glassfish.jersey.internal.Errors$1.call(Errors.java:271)
        at org.glassfish.jersey.internal.Errors$1.call(Errors.java:267)
        at org.glassfish.jersey.internal.Errors.process(Errors.java:315)
        at org.glassfish.jersey.internal.Errors.process(Errors.java:297)
        at org.glassfish.jersey.internal.Errors.process(Errors.java:267)
        at org.glassfish.jersey.process.internal.RequestScope.runInScope(RequestScope.java:320)
        at org.glassfish.jersey.client.ClientRuntime$2.run(ClientRuntime.java:201)
        at java.util.concurrent.Executors$RunnableAdapter.call(Executors.java:511)
        at java.util.concurrent.FutureTask.run(FutureTask.java:266)
        at java.util.concurrent.ThreadPoolExecutor.runWorker(ThreadPoolExecutor.java:1142)
        at java.util.concurrent.ThreadPoolExecutor$Worker.run(ThreadPoolExecutor.java:617)
        ... 1 more

Controller:

Aug 26, 2015 12:31:05 PM org.mongodb.morphia.logging.MorphiaLoggerFactory chooseLoggerFactory
INFORMATION: LoggerImplFactory set to org.mongodb.morphia.logging.jdk.JDKLoggerFactory
Exception in thread "main" java.lang.NullPointerException
        at io.minecloud.models.network.Network.deployServer(Network.java:79)
        at io.minecloud.controller.Controller.lambda$null$5(Controller.java:113)
        at java.util.stream.Streams$RangeIntSpliterator.forEachRemaining(Streams.java:110)
        at java.util.stream.IntPipeline$Head.forEach(IntPipeline.java:557)
        at io.minecloud.controller.Controller.lambda$null$6(Controller.java:106)
        at java.util.ArrayList.forEach(ArrayList.java:1249)
        at io.minecloud.controller.Controller.lambda$new$7(Controller.java:77)
        at java.util.ArrayList.forEach(ArrayList.java:1249)
        at io.minecloud.controller.Controller.<init>(Controller.java:63)
        at io.minecloud.controller.Controller.main(Controller.java:159)

Thats are in the .err logs, main Logs are empty but exists.

**Comment by ghost** [comment]
#push
